export default {
  SET_LOGGED_USER: "SET_LOGGED_USER",
  SET_INITAL_POLLS: "SET_INITAL_POLLS",
  SET_INITAL_USERS: "SET_INITAL_USERS",
  ANSWER_QUESTION: "ANSWER_QUESTION",
  ADD_QUESTION: "ADD_QUESTION",
  LOG_OUT: "LOG_OUT",
  CREATE_QUESTION: "CREATE_QUESTION"
};
